name: First CI pipeline

on: [push, pull_request]

jobs:
  build:
    name: app Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y default-jdk